apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue
  ports:
    - name: grpc-catalogue
      protocol: TCP
      port: 50051
      targetPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calalogue
  labels:
    app: catalogue
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      version: v1
  template:
    metadata:
      labels:
        app: catalogue
        version: v1
    spec:
      containers:
        - name: catalogue
          image: gihyo-ms-dev-book/catalogue:0.1
          env:
            - name: DATABASE
              value: "catalogue_user:default_password@tcp(catalogue-db:3306)/booksdb"
          ports:
            - containerPort: 50051
          livenessProbe:
            httpGet:
              path: /health
              port: 50051
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 50051
            initialDelaySeconds: 10
